import Foundation
import Testing
@testable import Domain

/// The palette is a projection of `CommandCatalog`, and these tests exist to keep it one.
@Suite("Command palette")
struct CommandPaletteTests {

    // MARK: - Derived, not maintained

    /// #49's acceptance criterion: *"a catalog entry added later appears in the palette with no
    /// palette code change."* Asserted as an identity rather than a spot check — a test that named
    /// three commands would pass forever while the palette silently missed the fourth.
    @Test("Every catalog command is offered, and nothing else is")
    func paletteIsExactlyTheCatalog() {
        let catalogNames = CommandCatalog.descriptors.map(\.name)
        let paletteNames = CommandPalette.entries.map(\.descriptor.name)

        #expect(paletteNames == catalogNames)
        #expect(CommandPalette.entries.count == CommandCatalog.descriptors.count)
    }

    @Test("An empty query offers everything, in catalog order")
    func emptyQueryReturnsCatalogOrder() {
        #expect(CommandPalette.matches("").map(\.id) == CommandCatalog.descriptors.map(\.name))
        // Whitespace is not a query. Someone who has typed a space and deleted their text should see
        // the full list back, not an empty palette.
        #expect(CommandPalette.matches("   ").count == CommandCatalog.descriptors.count)
    }

    // MARK: - Titles

    @Test("Catalog names are spelled for a human")
    func titlesAreHumanised() {
        #expect(CommandPaletteEntry.humanise("endpointCreateFromLog") == "Endpoint: create from log")
        #expect(CommandPaletteEntry.humanise("journeyAddTemplate") == "Journey: add template")
        #expect(CommandPaletteEntry.humanise("serverStart") == "Server: start")
        // A single-word command has no group to split off.
        #expect(CommandPaletteEntry.humanise("ping") == "Ping")
        #expect(CommandPaletteEntry.humanise("state") == "State")
    }

    /// House style is sentence case inside the window. A palette that rendered "Endpoint: Create From
    /// Log" would be the one place the rule broke, and it would be Title Case generated by code rather
    /// than typed by a person — which is the kind that survives review.
    @Test("No title is Title Case after the group")
    func titlesStaySentenceCase() {
        for entry in CommandPalette.entries {
            // Only the part *after* a group. A single-word command like "Ping" has no group, so the
            // whole title is the sentence's first word and is correctly capitalised — the first
            // version of this test flagged all three of those and was wrong, not the code.
            guard let colon = entry.title.firstIndex(of: ":") else { continue }
            let tail = entry.title[entry.title.index(after: colon)...]
            let words = tail.split(separator: " ")
            #expect(!words.isEmpty)
            #expect(words.allSatisfy { $0.first?.isUppercase != true }, "Title Case in \(entry.title)")
        }
    }

    // MARK: - Matching

    @Test("A prefix of the command name ranks first")
    func prefixWins() {
        let results = CommandPalette.matches("serverstart")
        #expect(results.first?.id == "serverStart")
    }

    /// The power-user path: initials of the humanised words.
    @Test("An acronym finds the command")
    func acronymMatches() {
        #expect(CommandPalette.matches("jat").contains { $0.id == "journeyAddTemplate" })
        #expect(CommandPalette.matches("sc").contains { $0.id == "scenarioCreate" })
    }

    @Test("A subsequence finds the command when a prefix does not")
    func subsequenceMatches() {
        // Not a prefix of anything, but in order inside `journeyDuplicate`.
        #expect(CommandPalette.matches("jrndup").contains { $0.id == "journeyDuplicate" })
    }

    /// Typing a word that appears in many summaries must not bury the commands actually named for it.
    @Test("A name match outranks a summary match")
    func nameOutranksSummary() {
        let results = CommandPalette.matches("delete")
        let firstSummaryOnly = results.firstIndex { !$0.descriptor.name.lowercased().contains("delete") }
        let lastNameMatch = results.lastIndex { $0.descriptor.name.lowercased().contains("delete") }

        if let firstSummaryOnly, let lastNameMatch {
            #expect(lastNameMatch < firstSummaryOnly)
        }
        #expect(results.contains { $0.id == "endpointDelete" })
    }

    @Test("A query that matches nothing returns nothing")
    func noMatchesReturnsEmpty() {
        #expect(CommandPalette.matches("zzqqxx").isEmpty)
    }

    /// `sorted(by:)` promises no stability, so equal scores need an explicit tie-break or the list can
    /// reshuffle between keystrokes that did not change it — and a list that moves under the selection
    /// is how you execute the wrong command.
    @Test("Ranking is deterministic across repeated calls")
    func rankingIsStable() {
        let once = CommandPalette.matches("e").map(\.id)
        let twice = CommandPalette.matches("e").map(\.id)
        #expect(once == twice)
        #expect(once.count > 1)
    }

    // MARK: - Argument prompting

    /// A command whose parameters are all optional must run straight from a keystroke rather than
    /// stopping to ask for input it has defaults for.
    @Test("Only commands with a required parameter prompt for arguments")
    func requiredParametersDriveThePrompt() {
        func entry(_ name: String) -> CommandPaletteEntry? {
            CommandPalette.entries.first { $0.id == name }
        }

        #expect(entry("serverStop")?.requiresArguments == false)
        #expect(entry("projectList")?.requiresArguments == false)
        // `port?` is optional — starting the server must not demand one.
        #expect(entry("serverStart")?.requiresArguments == false)
        // `name` is not optional.
        #expect(entry("projectRename")?.requiresArguments == true)
        // `name?` and `spec?` are optional, `method` and `path` are not.
        #expect(entry("endpointCreate")?.requiresArguments == true)
    }

    @Test("Every entry carries the CLI spelling of the same operation")
    func entriesCarryTheCLIInvocation() {
        for entry in CommandPalette.entries {
            #expect(!entry.descriptor.cli.isEmpty)
            #expect(entry.descriptor.cli.hasPrefix("mimic "))
        }
    }
}

/// Constructing the command an entry stands for.
@Suite("Command palette execution")
struct CommandPaletteExecutionTests {

    /// The criterion that matters: an entry needing no arguments must be *runnable*, and by the same
    /// route the control API uses rather than a switch someone has to remember to extend.
    @Test("Every argument-free entry decodes into a real command")
    func argumentFreeEntriesConstruct() throws {
        let runnable = CommandPalette.entries.filter { !$0.requiresArguments }
        #expect(runnable.count > 5, "the catalog should have several no-argument commands")

        for entry in runnable {
            #expect(
                CommandPalette.command(for: entry) != nil,
                "\(entry.descriptor.name) is offered without a prompt but cannot be constructed"
            )
        }
    }

    @Test("An entry that needs arguments does not silently run without them")
    func argumentNeedingEntriesRefuse() {
        let prompting = CommandPalette.entries.filter(\.requiresArguments)
        #expect(!prompting.isEmpty)

        for entry in prompting {
            #expect(CommandPalette.command(for: entry) == nil)
        }
    }

    /// Spot-check that the decoded value is the command it claims to be, not merely non-nil — a
    /// decoder that fell back to some default case would satisfy the test above and be useless.
    @Test("The constructed command is the one named")
    func constructedCommandsAreCorrect() throws {
        func command(_ name: String) -> ControlCommand? {
            CommandPalette.entries.first { $0.id == name }.flatMap(CommandPalette.command(for:))
        }

        #expect(command("ping") == .ping)
        #expect(command("serverStop") == .serverStop)
        #expect(command("projectList") == .projectList)
    }
}
